
set(CMAKE_OSX_DEPLOYMENT_TARGET 10.12)

set(CMAKE_C_STANDARD 99)

add_compile_options(-fno-common)
add_compile_options(-Werror\=return-type)
add_compile_options(-Wunreachable-code)
add_compile_options(-Werror\=deprecated-objc-isa-usage)
add_compile_options(-Werror\=objc-root-class)
add_compile_options(-Wunused-variable)
add_compile_options(-Wempty-body)
add_compile_options(-Wuninitialized)
add_compile_options(-Wconditional-uninitialized)
add_compile_options(-Wconstant-conversion)
add_compile_options(-Wint-conversion)
add_compile_options(-Wbool-conversion)
add_compile_options(-Wenum-conversion)
add_compile_options(-Wobjc-literal-conversion)
add_compile_options(-Wshorten-64-to-32)
add_compile_options(-Winfinite-recursion)
add_compile_options(-Wcomma)
add_compile_options(-Wblock-capture-autoreleasing)
add_compile_options(-Wstrict-prototypes)
